name: build-deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Set up Node
      uses: actions/setup-node@main
      with:
        node-version: 20

    - name: Install Dependent Node Pkgs
      run: npm install
    
    - name: Build
      run: npm run docs:build

    - name: Commit and Push
      run: |-
        cd docs/.vuepress/dist
        echo -n 'dwdsec.top' > CNAME
        git init
        git add -A
        git commit -m 'deploy'
        git remote add origin https://github.com/DWDSec/DWDSec_WebSite.git
        git push -f origin master:gh-pages
